# Generated by Django 4.1.5 on 2023-04-27 07:14

import ckeditor.fields
import datetime
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AajKaRashifal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banners')),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 12, 44, 13, 720226), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddMashikPatrika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='PDF_Image/')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 12, 44, 13, 720226), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('ctg', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='advertisements')),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 12, 44, 13, 720226), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('description', ckeditor.fields.RichTextField()),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 12, 44, 13, 719226), null=True)),
                ('show_in_home', models.BooleanField(default=False, null=True)),
                ('show_in_headline', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
