# Generated by Django 4.1.5 on 2023-05-03 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFile', '0003_alter_addbanner_created_at_alter_addvideo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbanner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 8, 49, 27, 912245), null=True),
        ),
        migrations.AlterField(
            model_name='addvideo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 8, 49, 27, 913245), null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 8, 49, 27, 912245), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 8, 49, 27, 911244), null=True),
        ),
    ]
