# Generated by Django 4.1.5 on 2023-05-03 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFile', '0004_alter_addbanner_created_at_alter_addvideo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbanner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 30, 8, 498482), null=True),
        ),
        migrations.AlterField(
            model_name='addvideo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 30, 8, 499483), null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 30, 8, 498482), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 30, 8, 497480), null=True),
        ),
    ]
